version: '3.9'

services:
  auth-service:
    image: jhoniel/auth-service:v1.5  
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    environment:
      - DB_HOST=auth-jhonel-9a28.d.aivencloud.com
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_UthH-rDErxsJvbLudmt
      - DB_PORT=28074
      - DB_NAME=defaultdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  qa-service:
    image: jhoniel/qa-service:v1.5 
    ports:
      - "3002:3002"
    networks:
      - mynetwork
    environment:
      - DB_HOST=auth-jhonel-9a28.d.aivencloud.com
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_UthH-rDErxsJvbLudmt
      - DB_PORT=28074
      - DB_NAME=defaultdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-proxy:
    image: jhoniel/api-proxy:v1.2
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure 

networks:
  mynetwork:
    driver: overlay